### PR TITLE
fix: alias set_acl_category type parameters to support more architectures

### LINKED ISSUE #139: Fix compile time mismatched types error when running "cargo build --all --all-targets  --release"
When running the command `cargo build --all --all-targets  --release`, I see this error below. It is likely from the recent ACL change and should be a small change to fix the casting.

```
error[E0308]: mismatched types
   --> src/context/mod.rs:504:74
    |
504 |             let command = raw::RedisModule_GetCommand.unwrap()(self.ctx, command_name);
    |                           ------------------------------------           ^^^^^^^^^^^^ expected `*const u8`, found `*const i8`
    |                           |
    |                           arguments to this function are incorrect
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`

error[E0308]: mismatched types
   --> src/context/mod.rs:505:72
    |
505 |             raw::RedisModule_SetCommandACLCategories.unwrap()(command, acl_flags).into()
    |             -------------------------------------------------          ^^^^^^^^^ expected `*const u8`, found `*const i8`
    |             |
    |             arguments to this function are incorrect
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`
```

### PR DESCRIPTION
**Pull request by hahnandrew**
Change `set_acl_category` parameters command_name and acl_flags to use `c_char` instead of `i8` to support builds for architectures where `c_char` is aliased to `u8`

fixes #139

### CODE REVIEW

**Comment by mkmkme** [comment]
I can check this on Windows this evening if they don't respond

**Comment by dmitrypol** [comment]
thank you @mkmkme

**Comment by mkmkme** [comment]
@dmitrypol FWIW `cargo build --all --all-targets  --release` fails on Windows for a different reason for me, and this PR does not fix it.
https://gist.githubusercontent.com/mkmkme/77f94b20659e717929abe8a69db426ac/raw/205c1005cecd22d3827ff1354c8cb1dc5b45357b/gistfile1.txt

**Comment by hahnandrew** [comment]
Supporting Windows is not in scope for this PR

**Comment by hahnandrew** [comment]
Fixing Windows build issues from the main branch is out of scope for this PR. AFAIK windows is a second class

**Comment by hahnandrew** [comment]
Fixing Windows build issues from the main branch is out of scope for this PR

File: src/context/mod.rs [hunk 1]
```diff
@@ -499,7 +499,7 @@ impl Context {
         feature = "min-redis-compatibility-version-7-2",
         feature = "min-valkey-compatibility-version-8-0"
     ),))]
-    pub fn set_acl_category(&self, command_name: *const i8, acl_flags: *const i8) -> raw::Status {
+    pub fn set_acl_category(&self, command_name: *const c_char, acl_flags: *const c_char) -> raw::Status {
```
Comment (KarthikSubbarao) [inline src/context/mod.rs:502]: This works for me.

I also saw that u8 works as an alternative

**Review by KarthikSubbarao — APPROVED** [review]

File: src/context/mod.rs (hunk 1 above)
Comment (hahnandrew) [reply src/context/mod.rs:502]: Thanks for confirming.

**Comment by dmitrypol** [comment]
I am going to merge this PR.  @mkmkme - could you please file a separate ticket for the Windows issue.
